#include "ModbusTCPGrpcService.h"
#include "Logger.h"
namespace ModbusTCP {
grpc::Status GrpcService::UpsertLink(grpc::ServerContext*, const ModbusTCPProto::UpsertLinkRequest* r, ModbusTCPProto::LinkInfo* o){ if(!module_||!r||!o)return {grpc::StatusCode::INVALID_ARGUMENT,"请求/模块为空"}; LOG_INFO("收到 ModbusTCP UpsertLink 请求: conn_name={}", r->config().conn_name()); auto s = module_->linkManager().UpsertLink(*r,o); LOG_INFO("ModbusTCP UpsertLink 响应: conn_name={}, ok={}, reason={}", r->config().conn_name(), s.ok(), s.ok()?"":s.error_message()); return s; }
grpc::Status GrpcService::RenameLink(grpc::ServerContext*, const ModbusTCPProto::RenameLinkRequest* r, ModbusTCPProto::LinkInfo* o){ if(!module_||!r||!o)return {grpc::StatusCode::INVALID_ARGUMENT,"请求/模块为空"}; return module_->linkManager().RenameLink(*r,o); }
grpc::Status GrpcService::GetLink(grpc::ServerContext*, const ModbusTCPProto::GetLinkRequest* r, ModbusTCPProto::LinkInfo* o){ if(!module_||!r||!o)return {grpc::StatusCode::INVALID_ARGUMENT,"请求/模块为空"}; return module_->linkManager().GetLink(r->conn_name(),o); }
grpc::Status GrpcService::ListLinks(grpc::ServerContext*, const ModbusTCPProto::Empty*, ModbusTCPProto::ListLinksResponse* o){ if(!module_||!o)return {grpc::StatusCode::INVALID_ARGUMENT,"模块/响应为空"}; return module_->linkManager().ListLinks(o); }
grpc::Status GrpcService::DeleteLink(grpc::ServerContext*, const ModbusTCPProto::DeleteLinkRequest* r, ModbusTCPProto::Empty*){ if(!module_||!r)return {grpc::StatusCode::INVALID_ARGUMENT,"请求为空"}; return module_->linkManager().DeleteLink(r->conn_name()); }
grpc::Status GrpcService::StartLink(grpc::ServerContext*, const ModbusTCPProto::StartLinkRequest* r, ModbusTCPProto::Empty*){ if(!module_||!r)return {grpc::StatusCode::INVALID_ARGUMENT,"请求为空"}; return module_->linkManager().StartLink(r->conn_name()); }
grpc::Status GrpcService::StopLink(grpc::ServerContext*, const ModbusTCPProto::StopLinkRequest* r, ModbusTCPProto::Empty*){ if(!module_||!r)return {grpc::StatusCode::INVALID_ARGUMENT,"请求为空"}; return module_->linkManager().StopLink(r->conn_name()); }
grpc::Status GrpcService::UpsertPointTable(grpc::ServerContext*, const ModbusTCPProto::UpsertPointTableRequest* r, ModbusTCPProto::Empty*){ if(!module_||!r)return {grpc::StatusCode::INVALID_ARGUMENT,"请求为空"}; return module_->linkManager().UpsertPointTable(*r); }
grpc::Status GrpcService::GetPointTable(grpc::ServerContext*, const ModbusTCPProto::GetPointTableRequest* r, ModbusTCPProto::PointTable* o){ if(!module_||!r||!o)return {grpc::StatusCode::INVALID_ARGUMENT,"请求/响应为空"}; return module_->linkManager().GetPointTable(r->conn_name(),o); }
grpc::Status CommandService::ExecuteCommand(grpc::ServerContext*, const DataCenterProto::ExecuteCommandRequest* r, DataCenterProto::ExecuteCommandResponse* o){ if(!module_||!r||!o)return {grpc::StatusCode::INVALID_ARGUMENT,"请求/响应为空"}; LOG_INFO("收到 ModbusTCP 同步命令请求: conn_name={}, conn_id={}, tag={}, request_id={}", r->dst().conn_name(), r->dst().conn_id(), r->dst().tag(), r->request_id()); auto s = module_->linkManager().ExecuteCommand(*r,o); LOG_INFO("ModbusTCP 同步命令响应: status={}, ok={}, reason={}", static_cast<int>(o->status()), s.ok(), s.ok()?o->reason():s.error_message()); return s; }
}
