set(MODULE_MANAGER_VERSION_MAJOR 1)
set(MODULE_MANAGER_VERSION_MINOR 0)
set(MODULE_MANAGER_VERSION_PATCH 0)
set(MODULE_MANAGER_VERSION "${MODULE_MANAGER_VERSION_MAJOR}.${MODULE_MANAGER_VERSION_MINOR}.${MODULE_MANAGER_VERSION_PATCH}")