syntax = "proto3";

package ModuleManagerProto;

// 请求消息
message HelloRequest {
  string          name  = 1;
}

// 响应消息
message HelloReply {
  string message   = 1;
}

// 测试服务
service Greeter {
  // 简单RPC
  rpc SayHello (HelloRequest) returns (HelloReply) {}

  // 服务器端流式RPC
  rpc SayHelloStream (HelloRequest) returns (stream HelloReply) {}

  // 客户端端流式RPC
  rpc SayHelloClientStream (stream HelloRequest) returns (HelloReply) {}

  // 双向流式RPC
  rpc SayHelloBidiStream (stream HelloRequest) returns (stream HelloReply) {}
}
