if(NOT DEFINED MSKDSP_COVERAGE_ROOT)
  set(MSKDSP_COVERAGE_ROOT "${CMAKE_BINARY_DIR}")
endif()

file(GLOB_RECURSE MSKDSP_GCDA_FILES "${MSKDSP_COVERAGE_ROOT}/*.gcda")
if(MSKDSP_GCDA_FILES)
  file(REMOVE ${MSKDSP_GCDA_FILES})
endif()
